#!/usr/bin/env bash
LC_ALL=C

for i in $(ls -p /etc/fstab.d | grep -v /); do
	mount -aT $i
done
source /usr/bin/miarranque-swap &
if [[ -d /lib/live/mount/rootfs ]]; then
	source /usr/bin/miarranque-mem &
fi
