#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
IFS=" "
for i in $(ls -p /etc/fstab.d | grep -v /); do
	mount -aT $i
done
source /usr/bin/miarranque-swap &
if [[ -d /lib/live/mount/rootfs ]]; then
	source /usr/bin/miarranque-mem &
fi
